### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-postgrad-business-analyst#2]
## Introduction
Right now the introduction has a good explanation of what a Business Analyst is, but doesn't compare/contrast that with other roles. Some points about Business Analyst that I think should be included (possibly worded differently) are:

- Domain knowledge (knowledge of the business and the market) is very important
- Visualization and communication is very important
- Business Analysts are less likely to use Python, statistics, machine learning, or Big Data than other roles

## Business (Intelligence) Analyst Sample Job Descriptions
The two job descriptions all kind of blur together. Is there something you could add to break that up visually? Maybe moving the job titles (e.g. Junior Business Intelligence Analyst) out of the block quote, maybe adding a sentence describing why each example was selected

## Business Analyst Resources
Ideally it would be a little clearer why you might choose one of these tools over another. Right now the descriptions all sound fairly similar. But this is a low-priority edit in my opinion

**Comment by Cheffrey2000** [comment]
Resolved with PR #3
